# Agentic AI System Configuration
# Made with ❤️ by Mulky Malikul Dhaher in Indonesia 🇮🇩

system:
  name: "Agentic AI System"
  version: "1.0.0"
  author: "Mulky Malikul Dhaher"
  country: "Indonesia"

agents:
  agent_base:
    name: "Agent Base"
    role: "Master Controller & Task Coordinator" 
    emoji: "🎯"
    description: "Main coordinator for all agent activities"
    
  agent_02_meta_spawner:
    name: "Agent 02 (Meta-Spawner)"
    role: "Performance Monitor & Meta-Analysis"
    emoji: "📊"
    description: "System monitoring and performance analysis"
    
  agent_03_planner:
    name: "Agent 03 (Planner)"
    role: "Strategic Planning & Goal Breakdown"
    emoji: "📋"
    description: "Task planning and strategic coordination"
    
  agent_04_executor:
    name: "Agent 04 (Executor)"
    role: "Task Execution & Implementation"
    emoji: "⚙️"
    description: "Execute scripts, APIs, and automation tasks"
    
  agent_05_designer:
    name: "Agent 05 (Designer)"
    role: "Visual Creation & UI Design"
    emoji: "🎨"
    description: "Create visual assets and user interfaces"
    
  agent_06_specialist:
    name: "Agent 06 (Specialist)"
    role: "Domain Expert & Consultant"
    emoji: "🔬"
    description: "Specialized knowledge and expert consultation"
    
  output_handler:
    name: "Output Handler"
    role: "Result Compilation & Formatting"
    emoji: "📤"
    description: "Compile and format final deliverables"

workflow:
  standard_process:
    - step: "Planning"
      agent: "agent_03_planner"
      action: "Create detailed execution plan"
      critical: true
      
    - step: "Execution"
      agent: "agent_04_executor"
      action: "Execute planned tasks"
      critical: true
      
    - step: "Output Processing"
      agent: "output_handler"
      action: "Compile final results"
      critical: false

  development_workflow:
    - step: "Requirements Analysis"
      agent: "agent_03_planner"
      action: "Analyze project requirements"
      critical: true
      
    - step: "Design Creation"
      agent: "agent_05_designer"
      action: "Create system design"
      critical: false
      
    - step: "Implementation"
      agent: "agent_04_executor"
      action: "Implement solution"
      critical: true
      
    - step: "Specialist Review"
      agent: "agent_06_specialist"
      action: "Review and validate"
      critical: false
      
    - step: "Final Output"
      agent: "output_handler"
      action: "Package deliverables"
      critical: true

external_apis:
  wikipedia:
    enabled: true
    base_url: "https://en.wikipedia.org/api/rest_v1"
    
  news:
    enabled: true
    base_url: "https://newsapi.org/v2"
    
  quotes:
    enabled: true
    base_url: "https://api.quotable.io"

security:
  encryption: "AES-256"
  key_derivation: "PBKDF2"
  iterations: 100000

features:
  memory_system: true
  knowledge_enrichment: true
  multi_agent_coordination: true
  web_automation: false  # Disabled until properly implemented
  platform_integrations: false  # Disabled until properly implemented
